baseURL = 'https://nursyah21.github.io/nursyah-blog/'
languageCode = 'en-us'
title = 'My Coding Journey'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

disqusShortName = 'nursyah'

[taxonomies]
tag = 'tag'
category = 'categories'

[params]
   # commentoEnable = true

[[params.ananke_socials]]
name = 'github'
url = 'https://github.com/nursyah21'
