baseURL = 'https://nursyah21.github.io/nursyah-blog/'
languageCode = 'en-us'
title = 'My Coding Journey'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

Paginate = 6
enableRobotsTXT = true

disqusShortName = 'nursyah'
[params]
   recent_posts_number = 6
   dateFormat = "02 Jan 2006"

   # commentoEnable = true

[[params.ananke_socials]]
name = 'github'
url = 'https://github.com/nursyah21'
