baseURL = 'https://nursyah21.github.io/nursyah-blog/'
languageCode = 'en-us'
title = 'My Coding Journey'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

#disqusShortName = 'nursyah'
[params]
   # commentoEnable = true
